# Stubs for django.http.cookie (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from http import cookies
from typing import Any

SimpleCookie = cookies.SimpleCookie

def parse_cookie(cookie: Any): ...
