# Stubs for django.db.models.functions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .comparison import Cast as Cast, Coalesce as Coalesce, Greatest as Greatest, Least as Least
from .datetime import Extract as Extract, ExtractDay as ExtractDay, ExtractHour as ExtractHour, ExtractMinute as ExtractMinute, ExtractMonth as ExtractMonth, ExtractQuarter as ExtractQuarter, ExtractSecond as ExtractSecond, ExtractWeek as ExtractWeek, ExtractWeekDay as ExtractWeekDay, ExtractYear as ExtractYear, Now as Now, Trunc as Trunc, TruncDate as TruncDate, TruncDay as TruncDay, TruncHour as TruncHour, TruncMinute as TruncMinute, TruncMonth as TruncMonth, TruncQuarter as TruncQuarter, TruncSecond as TruncSecond, TruncTime as TruncTime, TruncWeek as TruncWeek, TruncYear as TruncYear
from .text import Chr as Chr, Concat as Concat, ConcatPair as ConcatPair, LPad as LPad, LTrim as LTrim, Left as Left, Length as Length, Lower as Lower, Ord as Ord, RPad as RPad, RTrim as RTrim, Repeat as Repeat, Replace as Replace, Right as Right, StrIndex as StrIndex, Substr as Substr, Trim as Trim, Upper as Upper
from .window import CumeDist as CumeDist, DenseRank as DenseRank, FirstValue as FirstValue, Lag as Lag, LastValue as LastValue, Lead as Lead, NthValue as NthValue, Ntile as Ntile, PercentRank as PercentRank, Rank as Rank, RowNumber as RowNumber
