# Stubs for django.contrib.admin.actions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def delete_selected(modeladmin: Any, request: Any, queryset: Any): ...
