# Stubs for django.contrib.admin.decorators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def register(*models: Any, site: Optional[Any] = ...): ...
