# Stubs for django.contrib.postgres.fields.mixins (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class CheckFieldDefaultMixin:
    def check(self, **kwargs: Any): ...
