# Stubs for django.contrib.postgres.fields.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class AttributeSetter:
    def __init__(self, name: Any, value: Any) -> None: ...
