# Stubs for django.contrib.flatpages.sitemaps (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.sitemaps import Sitemap

class FlatPageSitemap(Sitemap):
    def items(self): ...
