# Stubs for django.db.backends.oracle.validation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.validation import BaseDatabaseValidation
from typing import Any

class DatabaseValidation(BaseDatabaseValidation):
    def check_field_type(self, field: Any, field_type: Any): ...
