# Stubs for django.contrib.auth.checks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .management import _get_builtin_permissions
from typing import Any, Optional

def check_user_model(app_configs: Optional[Any] = ..., **kwargs: Any): ...
def check_models_permissions(app_configs: Optional[Any] = ..., **kwargs: Any): ...
