# Stubs for django.contrib.auth.signals (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

user_logged_in: Any
user_login_failed: Any
user_logged_out: Any
