# Stubs for django.contrib.gis.geoip2.resources (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def City(response: Any): ...
def Country(response: Any): ...
