# Stubs for django.contrib.messages (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.messages.api import *
from django.contrib.messages.constants import *

default_app_config: str
