# Stubs for django.contrib.messages.constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

DEBUG: int
INFO: int
SUCCESS: int
WARNING: int
ERROR: int
DEFAULT_TAGS: Any
DEFAULT_LEVELS: Any
