# Stubs for django.contrib.messages.context_processors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def messages(request: Any): ...
