# Stubs for django.contrib.messages.views (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class SuccessMessageMixin:
    success_message: str = ...
    def form_valid(self, form: Any): ...
    def get_success_message(self, cleaned_data: Any): ...
