# Stubs for django.contrib.admin.views.decorators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def staff_member_required(view_func: Optional[Any] = ..., redirect_field_name: Any = ..., login_url: str = ...): ...
