# Stubs for django.contrib.gis.db.backends.spatialite.client (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.sqlite3.client import DatabaseClient

class SpatiaLiteClient(DatabaseClient):
    executable_name: str = ...
