# Stubs for django.db (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.utils import DEFAULT_DB_ALIAS as DEFAULT_DB_ALIAS, DJANGO_VERSION_PICKLE_KEY as DJANGO_VERSION_PICKLE_KEY, DataError as DataError, DatabaseError as DatabaseError, Error as Error, IntegrityError as IntegrityError, InterfaceError as InterfaceError, InternalError as InternalError, NotSupportedError as NotSupportedError, OperationalError as OperationalError, ProgrammingError as ProgrammingError
from typing import Any

connections: Any
router: Any

class DefaultConnectionProxy:
    def __getattr__(self, item: Any): ...
    def __setattr__(self, name: Any, value: Any): ...
    def __delattr__(self, name: Any): ...
    def __eq__(self, other: Any): ...

connection: Any
