# Stubs for django.middleware.clickjacking (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

class XFrameOptionsMiddleware(MiddlewareMixin):
    def process_response(self, request: Any, response: Any): ...
    def get_xframe_options_value(self, request: Any, response: Any): ...
