# Stubs for django.middleware.csrf (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

logger: Any
REASON_NO_REFERER: str
REASON_BAD_REFERER: str
REASON_NO_CSRF_COOKIE: str
REASON_BAD_TOKEN: str
REASON_MALFORMED_REFERER: str
REASON_INSECURE_REFERER: str
CSRF_SECRET_LENGTH: int
CSRF_TOKEN_LENGTH: Any
CSRF_ALLOWED_CHARS: Any
CSRF_SESSION_KEY: str

def get_token(request: Any): ...
def rotate_token(request: Any) -> None: ...

class CsrfViewMiddleware(MiddlewareMixin):
    def process_request(self, request: Any) -> None: ...
    def process_view(self, request: Any, callback: Any, callback_args: Any, callback_kwargs: Any): ...
    def process_response(self, request: Any, response: Any): ...
