# Stubs for django.middleware.gzip (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

re_accepts_gzip: Any

class GZipMiddleware(MiddlewareMixin):
    def process_response(self, request: Any, response: Any): ...
