# Stubs for django.middleware.http (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

class ConditionalGetMiddleware(MiddlewareMixin):
    def process_response(self, request: Any, response: Any): ...
    def needs_etag(self, response: Any): ...
