# Stubs for django.middleware.locale (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

class LocaleMiddleware(MiddlewareMixin):
    response_redirect_class: Any = ...
    def process_request(self, request: Any) -> None: ...
    def process_response(self, request: Any, response: Any): ...
