# Stubs for django.db.backends.sqlite3.creation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.creation import BaseDatabaseCreation
from typing import Any

class DatabaseCreation(BaseDatabaseCreation):
    @staticmethod
    def is_in_memory_db(database_name: Any): ...
    def get_test_db_clone_settings(self, suffix: Any): ...
    def test_db_signature(self): ...
