# Stubs for django.core.signals (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

request_started: Any
request_finished: Any
got_request_exception: Any
setting_changed: Any
