# Stubs for django.core.checks.security.csrf (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

W003: Any
W016: Any

def check_csrf_middleware(app_configs: Any, **kwargs: Any): ...
def check_csrf_cookie_secure(app_configs: Any, **kwargs: Any): ...
