# Stubs for django.core.checks.security.sessions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def add_session_cookie_message(message: Any): ...

W010: Any
W011: Any
W012: Any

def add_httponly_message(message: Any): ...

W013: Any
W014: Any
W015: Any

def check_session_cookie_secure(app_configs: Any, **kwargs: Any): ...
def check_session_cookie_httponly(app_configs: Any, **kwargs: Any): ...
