# Stubs for django.contrib.staticfiles.checks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def check_finders(app_configs: Optional[Any] = ..., **kwargs: Any): ...
