# Stubs for django.contrib.staticfiles.testing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.test import LiveServerTestCase
from typing import Any

class StaticLiveServerTestCase(LiveServerTestCase):
    static_handler: Any = ...
