# Stubs for django.contrib.staticfiles.views (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def serve(request: Any, path: Any, insecure: bool = ..., **kwargs: Any): ...
