# Stubs for django.conf.locale.bn.formats (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

DATE_FORMAT: str
TIME_FORMAT: str
YEAR_MONTH_FORMAT: str
MONTH_DAY_FORMAT: str
SHORT_DATE_FORMAT: str
FIRST_DAY_OF_WEEK: int
DATE_INPUT_FORMATS: Any
TIME_INPUT_FORMATS: Any
DATETIME_INPUT_FORMATS: Any
DECIMAL_SEPARATOR: str
THOUSAND_SEPARATOR: str
