# Stubs for django.contrib.contenttypes.migrations.0002_remove_content_type_name (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db import migrations
from typing import Any

def add_legacy_name(apps: Any, schema_editor: Any) -> None: ...

class Migration(migrations.Migration):
    dependencies: Any = ...
    operations: Any = ...
