# Stubs for django.contrib.contenttypes.checks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def check_generic_foreign_keys(app_configs: Optional[Any] = ..., **kwargs: Any): ...
def check_model_name_lengths(app_configs: Optional[Any] = ..., **kwargs: Any): ...
