# Stubs for django.core.files.images (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.files import File
from typing import Any

class ImageFile(File):
    @property
    def width(self): ...
    @property
    def height(self): ...

def get_image_dimensions(file_or_path: Any, close: bool = ...): ...
