# Stubs for django.core.files.locks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ctypes import Structure, Union, c_int64, c_ulong, c_void_p
from typing import Any

LOCK_SH: int
LOCK_NB: int
LOCK_EX: int
ULONG_PTR = c_int64
ULONG_PTR = c_ulong
PVOID = c_void_p

class _OFFSET(Structure): ...
class _OFFSET_UNION(Union): ...
class OVERLAPPED(Structure): ...

def lock(f: Any, flags: Any): ...
def unlock(f: Any): ...
