# Stubs for django.core.files.move (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def file_move_safe(old_file_name: Any, new_file_name: Any, chunk_size: Any = ..., allow_overwrite: bool = ...) -> None: ...
