# Stubs for django.db.models.sql (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models.sql.query import *
from django.db.models.sql.subqueries import *
from django.core.exceptions import EmptyResultSet as EmptyResultSet
from django.db.models.sql.where import AND as AND, OR as OR

# Names in __all__ with no definition:
#   Query
