# Stubs for django.db.models.sql.constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

GET_ITERATOR_CHUNK_SIZE: int
MULTI: str
SINGLE: str
CURSOR: str
NO_RESULTS: str
ORDER_PATTERN: Any
ORDER_DIR: Any
INNER: str
LOUTER: str
