# Stubs for django.contrib.admindocs.middleware (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import get_view_name
from django.utils.deprecation import MiddlewareMixin
from typing import Any

class XViewMiddleware(MiddlewareMixin):
    def process_view(self, request: Any, view_func: Any, view_args: Any, view_kwargs: Any): ...
