# Stubs for django.contrib.redirects.apps (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.apps import AppConfig
from typing import Any

class RedirectsConfig(AppConfig):
    name: str = ...
    verbose_name: Any = ...
