# Stubs for django.test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.test.client import Client as Client, RequestFactory as RequestFactory
from django.test.testcases import LiveServerTestCase as LiveServerTestCase, SimpleTestCase as SimpleTestCase, TestCase as TestCase, TransactionTestCase as TransactionTestCase, skipIfDBFeature as skipIfDBFeature, skipUnlessAnyDBFeature as skipUnlessAnyDBFeature, skipUnlessDBFeature as skipUnlessDBFeature
from django.test.utils import ignore_warnings as ignore_warnings, modify_settings as modify_settings, override_settings as override_settings, override_system_checks as override_system_checks, tag as tag
