# Stubs for django.contrib.sessions.serializers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.signing import JSONSerializer as BaseJSONSerializer
from typing import Any

class PickleSerializer:
    def dumps(self, obj: Any): ...
    def loads(self, data: Any): ...
JSONSerializer = BaseJSONSerializer
