# Stubs for django.db.migrations (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .operations import *
from .migration import Migration, swappable_dependency
