# Stubs for django.db.migrations.optimizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class MigrationOptimizer:
    def optimize(self, operations: Any, app_label: Optional[Any] = ...): ...
    def optimize_inner(self, operations: Any, app_label: Optional[Any] = ...): ...
