# Stubs for django.db.migrations.topological_sort (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def topological_sort_as_sets(dependency_graph: Any) -> None: ...
def stable_topological_sort(l: Any, dependency_graph: Any): ...
