# Stubs for django.urls.conf (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .resolvers import LocalePrefixPattern, RegexPattern, RoutePattern, URLPattern, URLResolver
from typing import Any, Optional

def include(arg: Any, namespace: Optional[Any] = ...): ...

path: Any
re_path: Any
