# Stubs for django.urls.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def get_callable(lookup_view: Any): ...
def get_mod_func(callback: Any): ...
