# Stubs for django.contrib.sites.management (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def create_default_site(app_config: Any, verbosity: int = ..., interactive: bool = ..., using: Any = ..., apps: Any = ..., **kwargs: Any) -> None: ...
