# Stubs for django.contrib.staticfiles.templatetags.staticfiles (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register: Any

def static(path: Any): ...
def do_static(parser: Any, token: Any): ...
