# Stubs for django.db.backends.postgresql.client (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.client import BaseDatabaseClient
from typing import Any

class DatabaseClient(BaseDatabaseClient):
    executable_name: str = ...
    @classmethod
    def runshell_db(cls, conn_params: Any) -> None: ...
    def runshell(self) -> None: ...
