# Stubs for django.db.backends.postgresql.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def utc_tzinfo_factory(offset: Any): ...
