# Stubs for django.utils.baseconv (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

BASE2_ALPHABET: str
BASE16_ALPHABET: str
BASE56_ALPHABET: str
BASE36_ALPHABET: str
BASE62_ALPHABET: str
BASE64_ALPHABET: Any

class BaseConverter:
    decimal_digits: str = ...
    sign: Any = ...
    digits: Any = ...
    def __init__(self, digits: Any, sign: str = ...) -> None: ...
    def encode(self, i: Any): ...
    def decode(self, s: Any): ...
    def convert(self, number: Any, from_digits: Any, to_digits: Any, sign: Any): ...

base2: Any
base16: Any
base36: Any
base56: Any
base62: Any
base64: Any
