# Stubs for django.utils.dateparse (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

date_re: Any
time_re: Any
datetime_re: Any
standard_duration_re: Any
iso8601_duration_re: Any
postgres_interval_re: Any

def parse_date(value: Any): ...
def parse_time(value: Any): ...
def parse_datetime(value: Any): ...
def parse_duration(value: Any): ...
