# Stubs for django.utils.dates (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

WEEKDAYS: Any
WEEKDAYS_ABBR: Any
MONTHS: Any
MONTHS_3: Any
MONTHS_AP: Any
MONTHS_ALT: Any
