# Stubs for django.utils.deconstruct (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def deconstructible(*args: Any, path: Optional[Any] = ...): ...
