# Stubs for django.utils.numberformat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def format(number: Any, decimal_sep: Any, decimal_pos: Optional[Any] = ..., grouping: int = ..., thousand_sep: str = ..., force_grouping: bool = ..., use_l10n: Optional[Any] = ...): ...
