# Stubs for django.utils.safestring (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class SafeData:
    def __html__(self): ...

class SafeBytes(bytes, SafeData):
    def __add__(self, rhs: Any): ...

class SafeText(str, SafeData):
    def __add__(self, rhs: Any): ...
SafeString = SafeText

def mark_safe(s: Any): ...
