# Stubs for django.conf.locale.bg.formats (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

DATE_FORMAT: str
TIME_FORMAT: str
MONTH_DAY_FORMAT: str
SHORT_DATE_FORMAT: str
DECIMAL_SEPARATOR: str
THOUSAND_SEPARATOR: str
