# Stubs for django.template.backends.dummy (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import string
from .base import BaseEngine
from .utils import csrf_input_lazy, csrf_token_lazy
from typing import Any, Optional

class TemplateStrings(BaseEngine):
    app_dirname: str = ...
    def __init__(self, params: Any) -> None: ...
    def from_string(self, template_code: Any): ...
    def get_template(self, template_name: Any): ...

class Template(string.Template):
    def render(self, context: Optional[Any] = ..., request: Optional[Any] = ...): ...
