# Stubs for django.template.backends.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def csrf_input(request: Any): ...

csrf_input_lazy: Any
csrf_token_lazy: Any
