# Stubs for django.contrib.gis.db.backends.postgis.const (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

GDAL_TO_POSTGIS: Any
POSTGIS_TO_GDAL: Any
POSTGIS_HEADER_STRUCTURE: str
GDAL_TO_STRUCT: Any
STRUCT_SIZE: Any
