# Stubs for django.contrib.postgres.apps (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .lookups import SearchLookup, TrigramSimilar, Unaccent
from .signals import register_type_handlers
from django.apps import AppConfig
from typing import Any

class PostgresConfig(AppConfig):
    name: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
