# Stubs for django.contrib.postgres.functions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models import Func
from typing import Any

class RandomUUID(Func):
    template: str = ...
    output_field: Any = ...

class TransactionNow(Func):
    template: str = ...
    output_field: Any = ...
