# Stubs for django.contrib.postgres.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def prefix_validation_error(error: Any, prefix: Any, code: Any, params: Any): ...
