# Stubs for django.contrib.gis.apps (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.apps import AppConfig
from typing import Any

class GISConfig(AppConfig):
    name: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
