# Stubs for django.contrib.gis.geometry (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

hex_regex: Any
wkt_regex: Any
json_regex: Any
