# Stubs for django.contrib.gis.views (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def feed(request: Any, url: Any, feed_dict: Optional[Any] = ...): ...
