# Stubs for django.contrib.admin.migrations.0002_logentry_remove_auto_add (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db import migrations
from typing import Any

class Migration(migrations.Migration):
    dependencies: Any = ...
    operations: Any = ...
