# Stubs for django.template.loaders.app_directories (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .filesystem import Loader as FilesystemLoader

class Loader(FilesystemLoader):
    def get_dirs(self): ...
