# Stubs for django.contrib.admin.templatetags.admin_static (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register: Any

def static(path: Any): ...
