# Stubs for django.contrib.admin.templatetags.admin_urls (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

register: Any

def admin_urlname(value: Any, arg: Any): ...
def admin_urlquote(value: Any): ...
def add_preserved_filters(context: Any, url: Any, popup: bool = ..., to_field: Optional[Any] = ...): ...
