# Stubs for django.contrib.admin.templatetags.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.template.library import InclusionNode
from typing import Any

class InclusionAdminNode(InclusionNode):
    template_name: Any = ...
    def __init__(self, parser: Any, token: Any, func: Any, template_name: Any, takes_context: bool = ...) -> None: ...
    def render(self, context: Any): ...
