# Stubs for django.core.mail.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class CachedDnsName:
    def get_fqdn(self): ...

DNS_NAME: Any
