# Stubs for django.db.backends.mysql.client (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.client import BaseDatabaseClient
from typing import Any

class DatabaseClient(BaseDatabaseClient):
    executable_name: str = ...
    @classmethod
    def settings_to_cmd_args(cls, settings_dict: Any): ...
    def runshell(self) -> None: ...
