# Stubs for django.core.checks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .messages import CRITICAL as CRITICAL, CheckMessage as CheckMessage, Critical as Critical, DEBUG as DEBUG, Debug as Debug, ERROR as ERROR, Error as Error, INFO as INFO, Info as Info, WARNING as WARNING, Warning as Warning
from .registry import Tags as Tags, register as register, run_checks as run_checks, tag_exists as tag_exists
