# Stubs for django.core.checks.caches (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

E001: Any

def check_default_cache_is_configured(app_configs: Any, **kwargs: Any): ...
