# Stubs for django.core.checks.database (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def check_database_backends(*args: Any, **kwargs: Any): ...
