# Stubs for django.core.checks.model_checks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def check_all_models(app_configs: Optional[Any] = ..., **kwargs: Any): ...
def check_lazy_references(app_configs: Optional[Any] = ..., **kwargs: Any): ...
