# Stubs for django.core.checks.templates (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

E001: Any
E002: Any

def check_setting_app_dirs_loaders(app_configs: Any, **kwargs: Any): ...
def check_string_if_invalid_is_string(app_configs: Any, **kwargs: Any): ...
