# Stubs for django.template (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import Context as Context, RequestContext as RequestContext, Template as Template
from .engine import Engine as Engine
from typing import Any

engines: Any
