# Stubs for django.db.models.signals (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.dispatch import Signal
from typing import Any, Optional

class_prepared: Any

class ModelSignal(Signal):
    def connect(self, receiver: Any, sender: Optional[Any] = ..., weak: bool = ..., dispatch_uid: Optional[Any] = ..., apps: Optional[Any] = ...) -> None: ...
    def disconnect(self, receiver: Optional[Any] = ..., sender: Optional[Any] = ..., dispatch_uid: Optional[Any] = ..., apps: Optional[Any] = ...): ...

pre_init: Any
post_init: Any
pre_save: Any
post_save: Any
pre_delete: Any
post_delete: Any
m2m_changed: Any
pre_migrate: Any
post_migrate: Any
