# Stubs for django.conf.urls (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.urls import include as include
from django.views import defaults
from typing import Any, Optional

handler400 = defaults.bad_request
handler403 = defaults.permission_denied
handler404 = defaults.page_not_found
handler500 = defaults.server_error

def url(regex: Any, view: Any, kwargs: Optional[Any] = ..., name: Optional[Any] = ...): ...
