# Stubs for django.conf.urls.static (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def static(prefix: Any, view: Any = ..., **kwargs: Any): ...
