# Stubs for django.contrib.auth.migrations.0003_alter_user_email_max_length (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db import migrations
from typing import Any

class Migration(migrations.Migration):
    dependencies: Any = ...
    operations: Any = ...
