# Stubs for django.contrib.auth.migrations.0005_alter_user_last_login_null (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db import migrations
from typing import Any

class Migration(migrations.Migration):
    dependencies: Any = ...
    operations: Any = ...
