# Stubs for django.contrib.auth.migrations.0006_require_contenttypes_0002 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db import migrations
from typing import Any

class Migration(migrations.Migration):
    dependencies: Any = ...
    operations: Any = ...
