# Stubs for django.contrib.auth.migrations.0007_alter_validators_add_error_messages (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db import migrations
from typing import Any

class Migration(migrations.Migration):
    dependencies: Any = ...
    operations: Any = ...
