# Stubs for django.db.migrations.operations.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def is_referenced_by_foreign_key(state: Any, model_name_lower: Any, field: Any, field_name: Any): ...
